[package]
name = "color"
version = "0.1.0"
authors = ["Nathan Graule <solarliner@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.27.0"

[dev-dependencies]
approx = "0.3.2"
csv = "1.1.1"
png = "0.15.0"
criterion = "0.2.11"

[[bench]]
name = "blackbody"
harness = false
